name: Build and Push Docker Image

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

```
permissions:
  contents: read
  packages: write   # สำคัญสำหรับ push GHCR

steps:
  - name: Checkout source code
    uses: actions/checkout@v4

  - name: Login to GHCR
    run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  - name: Build Docker Image
    run: |
      docker build -t ghcr.io/${{ github.repository }}:latest .

  - name: Push Docker Image
    run: |
      docker push ghcr.io/${{ github.repository }}:latest
```
